In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("downloads/CarPrice_Assignment.csv")
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [3]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [5]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

df['fueltype'] = label_encoder.fit_transform(df['fueltype'])
df['aspiration'] = label_encoder.fit_transform(df['aspiration'])
df['CarName'] = label_encoder.fit_transform(df['CarName'])
df['doornumber']=label_encoder.fit_transform(df['doornumber'])
df['enginetype']=label_encoder.fit_transform(df['enginetype'])
df['cylindernumber']=label_encoder.fit_transform(df['cylindernumber'])

In [7]:
one_hot_encoded_columns=['carbody','drivewheel','enginelocation','fuelsystem']
df= pd.get_dummies(df, columns=one_hot_encoded_columns,dtype=int)
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_front,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1,3,2,1,0,1,88.6,168.8,64.1,48.8,...,1,0,0,0,0,0,0,1,0,0
1,2,3,3,1,0,1,88.6,168.8,64.1,48.8,...,1,0,0,0,0,0,0,1,0,0
2,3,1,1,1,0,1,94.5,171.2,65.5,52.4,...,1,0,0,0,0,0,0,1,0,0
3,4,2,4,1,0,0,99.8,176.6,66.2,54.3,...,1,0,0,0,0,0,0,1,0,0
4,5,2,5,1,0,0,99.4,176.6,66.4,54.3,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,0,0,1,0,0
201,202,-1,138,1,1,0,109.1,188.8,68.8,55.5,...,1,0,0,0,0,0,0,1,0,0
202,203,-1,140,1,0,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,0,0,1,0,0
203,204,-1,142,0,1,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,1,0,0,0,0
204,205,-1,143,1,1,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,0,0,1,0,0

In [39]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_front,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1,3,2,1,0,1,88.6,168.8,64.1,48.8,...,1,0,0,0,0,0,0,1,0,0
1,2,3,3,1,0,1,88.6,168.8,64.1,48.8,...,1,0,0,0,0,0,0,1,0,0
2,3,1,1,1,0,1,94.5,171.2,65.5,52.4,...,1,0,0,0,0,0,0,1,0,0
3,4,2,4,1,0,0,99.8,176.6,66.2,54.3,...,1,0,0,0,0,0,0,1,0,0
4,5,2,5,1,0,0,99.4,176.6,66.4,54.3,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,0,0,1,0,0
201,202,-1,138,1,1,0,109.1,188.8,68.8,55.5,...,1,0,0,0,0,0,0,1,0,0
202,203,-1,140,1,0,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,0,0,1,0,0
203,204,-1,142,0,1,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,1,0,0,0,0
204,205,-1,143,1,1,0,109.1,188.8,68.9,55.5,...,1,0,0,0,0,0,0,1,0,0

In [8]:
mean = np.mean(df['price'])
print("mean=",mean)
std = np.std(df['price'])
print("standard deviation=",std)

mean= 13276.710570731706
standard deviation= 7969.34350572002

In [9]:
df["zscore"]=(df.price-mean)/std
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,zscore
0,1,3,2,1,0,1,88.6,168.8,64.1,48.8,...,0,0,0,0,0,0,1,0,0,0.027391
1,2,3,3,1,0,1,88.6,168.8,64.1,48.8,...,0,0,0,0,0,0,1,0,0,0.404461
2,3,1,1,1,0,1,94.5,171.2,65.5,52.4,...,0,0,0,0,0,0,1,0,0,0.404461
3,4,2,4,1,0,0,99.8,176.6,66.2,54.3,...,0,0,0,0,0,0,1,0,0,0.084485
4,5,2,5,1,0,0,99.4,176.6,66.4,54.3,...,0,0,0,0,0,0,1,0,0,0.523668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,0.447752
201,202,-1,138,1,1,0,109.1,188.8,68.8,55.5,...,0,0,0,0,0,0,1,0,0,0.723810
202,203,-1,140,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,1.029983
203,204,-1,142,0,1,0,109.1,188.8,68.9,55.5,...,0,0,0,0,1,0,0,0,0,1.153582
204,205,-1,143,1,1,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,1.173031

In [42]:
df[(df.zscore<-3)|(df.zscore>3)]

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,zscore
16,17,0,14,1,0,1,103.5,193.8,67.9,53.7,...,0,0,0,0,0,0,1,0,0,3.518268
73,74,0,18,1,0,0,120.9,208.1,71.7,56.7,...,0,0,0,0,0,0,1,0,0,3.473723
74,75,1,21,1,0,1,112.0,199.2,72.0,55.4,...,0,0,0,0,0,0,1,0,0,4.030858

In [13]:
without_outlier=df[(df.zscore>-3)&(df.zscore<3)]
df=without_outlier
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,zscore
0,1,3,2,1,0,1,88.6,168.8,64.1,48.8,...,0,0,0,0,0,0,1,0,0,0.027391
1,2,3,3,1,0,1,88.6,168.8,64.1,48.8,...,0,0,0,0,0,0,1,0,0,0.404461
2,3,1,1,1,0,1,94.5,171.2,65.5,52.4,...,0,0,0,0,0,0,1,0,0,0.404461
3,4,2,4,1,0,0,99.8,176.6,66.2,54.3,...,0,0,0,0,0,0,1,0,0,0.084485
4,5,2,5,1,0,0,99.4,176.6,66.4,54.3,...,0,0,0,0,0,0,1,0,0,0.523668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,0.447752
201,202,-1,138,1,1,0,109.1,188.8,68.8,55.5,...,0,0,0,0,0,0,1,0,0,0.723810
202,203,-1,140,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,1.029983
203,204,-1,142,0,1,0,109.1,188.8,68.9,55.5,...,0,0,0,0,1,0,0,0,0,1.153582
204,205,-1,143,1,1,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,1.173031

In [14]:
X=df.drop('price', axis=1)
y=df['price']
X

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,zscore
0,1,3,2,1,0,1,88.6,168.8,64.1,48.8,...,0,0,0,0,0,0,1,0,0,0.027391
1,2,3,3,1,0,1,88.6,168.8,64.1,48.8,...,0,0,0,0,0,0,1,0,0,0.404461
2,3,1,1,1,0,1,94.5,171.2,65.5,52.4,...,0,0,0,0,0,0,1,0,0,0.404461
3,4,2,4,1,0,0,99.8,176.6,66.2,54.3,...,0,0,0,0,0,0,1,0,0,0.084485
4,5,2,5,1,0,0,99.4,176.6,66.4,54.3,...,0,0,0,0,0,0,1,0,0,0.523668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,0.447752
201,202,-1,138,1,1,0,109.1,188.8,68.8,55.5,...,0,0,0,0,0,0,1,0,0,0.723810
202,203,-1,140,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,1.029983
203,204,-1,142,0,1,0,109.1,188.8,68.9,55.5,...,0,0,0,0,1,0,0,0,0,1.153582
204,205,-1,143,1,1,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,1.173031

In [15]:
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 202, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [17]:
# Split the dataset into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
X_train

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,zscore
202,203,-1,140,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,1.029983
39,40,0,44,1,0,0,96.5,175.4,65.2,54.1,...,0,1,0,0,0,0,0,0,0,-0.556095
25,26,1,29,1,0,0,93.7,157.3,63.8,50.6,...,0,0,1,0,0,0,0,0,0,-0.826255
125,126,3,98,1,0,1,94.5,168.9,68.3,50.2,...,0,0,0,0,0,0,1,0,0,1.096864
200,201,-1,139,1,0,0,109.1,188.8,68.9,55.5,...,0,0,0,0,0,0,1,0,0,0.447752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,110,0,86,1,0,0,114.2,198.9,68.4,58.7,...,0,0,0,0,0,0,1,0,0,-0.104991
14,15,1,15,1,0,0,103.5,189.0,66.9,55.7,...,0,0,0,0,0,0,1,0,0,1.416464
95,96,1,74,1,0,1,94.5,165.6,63.8,53.3,...,0,0,1,0,0,0,0,0,0,-0.687348
182,183,2,129,0,0,1,97.3,171.7,65.5,55.7,...,0,0,0,0,1,0,0,0,0,-0.690359
105,106,3,75,1,1,1,91.3,170.7,67.9,49.7,...,0,0,0,0,0,0,1,0,0,0.805874

In [19]:
X_test

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,wheelbase,carlength,carwidth,carheight,...,enginelocation_rear,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi,zscore
98,99,2,70,1,0,1,95.1,162.4,63.8,53.3,...,0,0,1,0,0,0,0,0,0,-0.630881
15,16,0,13,1,0,0,103.5,189.0,66.9,55.7,...,0,0,0,0,0,0,1,0,0,2.193818
31,32,2,43,1,0,1,86.6,144.6,63.9,50.8,...,0,1,0,0,0,0,0,0,0,-0.805802
162,163,0,125,1,0,0,95.7,166.3,64.4,52.8,...,0,0,1,0,0,0,0,0,0,-0.504271
189,190,3,145,1,0,1,94.5,159.3,64.2,55.6,...,0,0,0,0,0,0,1,0,0,-0.211022
118,119,1,92,1,0,1,93.7,157.3,63.8,50.8,...,0,0,1,0,0,0,0,0,0,-0.966794
70,71,-1,22,0,1,0,115.6,202.6,71.7,56.3,...,0,0,0,0,1,0,0,0,0,2.299222
175,176,-1,120,1,0,0,102.4,175.6,66.5,53.9,...,0,0,0,0,0,0,1,0,0,-0.412670
164,165,1,120,1,0,1,94.5,168.7,64.0,52.6,...,0,0,1,0,0,0,0,0,0,-0.632262
46,47,2,45,1,0,1,96.0,172.6,65.2,51.4,...,0,0,0,0,0,0,0,0,1,-0.279660
67,68,-1,19,0,1,0,110.0,190.9,70.3,56.5,...,0,0,0,0,1,0,0,0,0,1.540314
153,154,0,121,1,0,0,95.7,169.7,63.6,59.1,...,0,0,1,0,0,0,0,0,0,-0.797896
169,170,2,126,1,0,1,98.4,176.2,65.6,52.0,...,0,0,0,0,0,0,1,0,0,-0.412545
81,82,3,63,1,0,1,96.3,173.0,65.4,49.4,...,0,0,1,0,0,0,0,0,0,-0.599511
198,199,-2,143,1,1,0,104.3,188.8,67.2,56.2,...,0,0,0,0,0,0,1,0,0,0.645384
203,204,-1,142,0,1,0,109.1,188.8,68.9,55.5,...,0,0,0,0,1,0,0,0,0,1.153582
57,58,3,60,1,0,1,95.3,169.0,65.7,49.6,...,0,0,0,1,0,0,0,0,0,0.046213
156,157,0,125,1,0,0,95.7,166.3,64.4,53.0,...,0,0,1,0,0,0,0,0,0,-0.795387
85,86,1,67,1,0,0,96.3,172.4,65.4,51.6,...,0,0,1,0,0,0,0,0,0,-0.788987
69,70,0,16,0,1,1,106.7,187.5,70.3,54.9,...,0,0,0,0,1,0,0,0,0,1.869576
128,129,3,96,1,0,1,89.5,168.9,65.0,51.6,...,1,0,0,0,0,0,1,0,0,2.980332
17,18,0,12,1,0,0,110.0,197.0,70.9,56.3,...,0,0,0,0,0,0,1,0,0,2.961761
187,188,2,136,0,1,0,97.3,171.7,65.5,55.7,...,0,0,0,0,1,0,0,0,0,-0.474532
96,97,1,76,1,0,0,94.5,165.3,63.8,54.5,...,0,0,1,0,0,0,0,0,0,-0.724992
66,67,0,60,0,0,0,104.9,175.0,66.1,54.4,...,0,0,0,0,1,0,0,0,0,0.635848
61,62,1,56,1,0,1,98.8,177.8,66.5,53.7,...,0,0,1,0,0,0,0,0,0,-0.336503
87,88,1,68,1,1,0,96.3,172.4,65.4,51.6,...,0,0,0,0,0,0,0,1,0,-0.501636
68,69,-1,17,0,1,0,110.0,190.9,70.3,58.7,...,0,0,0,0,1,0,0,0,0,1.878610
129,130,1,97,1,0,1,98.4,175.7,72.3,50.5,...,0,0,0,0,0,0,1,0,0,2.274189
143,144,0,105,1,0,0,97.2,172.0,65.4,52.5,...,0,0,0,0,0,0,1,0,0,-0.416184
9,10,0,8,1,1,1,99.5,178.2,67.9,52.0,...,0,0,0,0,0,0,1,0,0,0.575011
19,20,1,25,1,0,1,94.5,155.9,63.6,52.0,...,0,0,1,0,0,0,0,0,0,-0.876071
56,57,3,54,1,0,1,95.3,169.0,65.7,49.6,...,0,0,0,1,0,0,0,0,0,-0.179652
78,79,2,68,1,0,1,93.7,157.3,64.4,50.8,...,0,0,1,0,0,0,0,0,0,-0.829141
167,168,2,122,1,0,1,98.4,176.2,65.6,52.0,...,0,0,0,0,0,0,1,0,0,-0.605785
107,108,0,85,1,0,0,107.9,186.7,68.4,56.7,...,0,0,0,0,0,0,1,0,0,-0.172751
139,140,2,107,1,0,1,93.7,157.9,63.6,53.7,...,0,0,1,0,0,0,0,0,0,-0.780956
141,142,0,104,1,0,0,97.2,172.0,65.4,52.5,...,0,0,1,0,0,0,0,0,0,-0.771796
168,169,2,115,1,0,1,98.4,176.2,65.6,52.0,...,0,0,0,0,0,0,1,0,0,-0.456463
79,80,1,63,1,1,1,93.0,157.3,63.8,50.8,...,0,0,0,0,0,0,0,1,0,-0.701151
82,83,3,68,1,1,1,95.9,173.2,66.3,50.2,...,0,0,0,0,0,0,0,1,0,-0.081275

In [21]:
y_train

202    21485.0
39      8845.0
25      6692.0
125    22018.0
200    16845.0
        ...
109    12440.0
14     24565.0
95      7799.0
182     7775.0
105    19699.0
Name: price, Length: 161, dtype: float64

In [23]:
y_test

98      8249.000
15     30760.000
31      6855.000
162     9258.000
189    11595.000
118     5572.000
70     31600.000
175     9988.000
164     8238.000
46     11048.000
67     25552.000
153     6918.000
169     9989.000
81      8499.000
198    18420.000
203    22470.000
57     13645.000
156     6938.000
85      6989.000
69     28176.000
128    37028.000
17     36880.000
187     9495.000
96      7499.000
66     18344.000
61     10595.000
87      9279.000
68     28248.000
129    31400.500
143     9960.000
9      17859.167
19      6295.000
56     11845.000
78      6669.000
167     8449.000
107    11900.000
139     7053.000
141     7126.000
168     9639.000
79      7689.000
82     12629.000
Name: price, dtype: float64

In [24]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler=MinMaxScaler()
# Perform feature scaling on X_train using MinMaxScaler
X_train_scaled_minmax = min_max_scaler.fit_transform(X_train)
X_train_scaled_minmax

array([[0.99019608, 0.2       , 0.95890411, ..., 0.        , 0.        ,
        0.5299851 ],
       [0.19117647, 0.4       , 0.30136986, ..., 0.        , 0.        ,
        0.12068519],
       [0.12254902, 0.6       , 0.19863014, ..., 0.        , 0.        ,
        0.0509682 ],
       ...,
       [0.46568627, 0.6       , 0.50684932, ..., 0.        , 0.        ,
        0.08681433],
       [0.89215686, 0.8       , 0.88356164, ..., 0.        , 0.        ,
        0.08603717],
       [0.51470588, 1.        , 0.51369863, ..., 0.        , 0.        ,
        0.47215206]])

In [25]:
X_test_scaled_minmax = min_max_scaler.fit_transform(X_test)
X_test_scaled_minmax

array([[0.45876289, 0.8       , 0.45255474, ..., 0.        , 0.        ,
        0.085103  ],
       [0.03092784, 0.4       , 0.03649635, ..., 0.        , 0.        ,
        0.80073754],
       [0.11340206, 0.8       , 0.25547445, ..., 0.        , 0.        ,
        0.04078713],
       ...,
       [0.81958763, 0.8       , 0.7810219 , ..., 0.        , 0.        ,
        0.12929171],
       [0.36082474, 0.6       , 0.40145985, ..., 1.        , 0.        ,
        0.06730036],
       [0.37628866, 1.        , 0.4379562 , ..., 1.        , 0.        ,
        0.22434512]])

In [ ]:
X_test=min_max_scaler.fit_transform(X_train)
X_train

In [45]:
X_test=min_max_scaler.transform(X_test)
X_test

array([[0.07352941, 0.4       , 0.0890411 , ..., 1.        , 0.        ,
        0.        ],
       [0.04411765, 0.4       , 0.05479452, ..., 1.        , 0.        ,
        0.        ],
       [0.49019608, 0.4       , 0.54109589, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.22058824, 0.4       , 0.31506849, ..., 0.        , 0.        ,
        0.        ],
       [0.41176471, 1.        , 0.45205479, ..., 0.        , 1.        ,
        0.        ],
       [0.71568627, 0.4       , 0.75342466, ..., 0.        , 0.        ,
        0.        ]])

In [27]:
# Build and train the multiple linear regression model
reg= LinearRegression()
reg.fit(X_train_scaled_minmax, y_train)

LinearRegression()

In [29]:
# Make predictions on the testing set
pred = reg.predict(X_test_scaled_minmax)

In [30]:
pred

array([ 7746.15087742, 29846.3766531 ,  6377.58818667,  8736.73893693,
       11031.09403611,  5118.        , 30671.04857579,  9453.41810783,
        7735.35160224, 10494.07553408, 24733.41073245,  6439.43858087,
        9454.39986012,  7991.58894964, 17731.55340793, 21707.65017803,
       13043.68622838,  6459.07362665,  6509.14299339, 27309.52873856,
       36000.        , 35854.70066124,  8969.4142294 ,  7009.83666073,
       17656.94023398, 10049.3417472 ,  8757.35573499, 27380.21490336,
       30475.18899415,  9425.92904374, 17180.95432649,  5827.80690488,
       11276.53210834,  6194.98226094,  7942.5013352 , 11330.52848423,
        6571.97513988,  6643.64305697,  9110.786559  ,  7196.36959563,
       12046.22590285])

In [31]:
reg.score(X_test_scaled_minmax,y_test)

0.9952144359692892

In [32]:
reg.coef_

array([ 4.61668713e-12,  5.68434189e-12, -2.44426701e-12, -1.29745104e-11,
       -4.26325641e-12, -4.81747975e-12, -6.84963197e-12, -3.87956334e-12,
        8.99191832e-12,  5.20117283e-12, -1.33688616e-11, -1.97992733e-11,
        6.43662901e-12,  3.72519793e-11, -6.22435437e-12, -2.89901436e-12,
       -3.09654524e-11, -7.03348491e-12, -3.69482223e-13,  2.28705943e-11,
       -1.21058719e-11, -2.02859951e-12,  5.01998443e-12, -2.44426701e-12,
        1.34470213e-12,  9.80548975e-13, -7.02016223e-12, -1.10276233e-11,
        1.00186526e-12,  9.47331102e-12, -6.08402217e-12, -5.45696821e-12,
       -2.34479103e-12, -1.16182619e-11,  1.03455022e-11, -2.21156427e-12,
        6.65068001e-12,  2.22488694e-12,  0.00000000e+00,  3.08820000e+04])

In [33]:
reg.intercept_

5118.000000000019

In [34]:
# Evaluate the model's performance
mse = mean_squared_error(y_test,pred)
mse

404420.74946125667

In [35]:
np.sqrt(mse)

635.9408380197459

In [ ]:
end